# Get summary of funding wallet
GET http://localhost:5040/funding-wallet

### publicIdentifier: indra8AXWmo3dFpK1drnjeWPyi9KTy9Fy3SkCydWx8waQrxhnW4KPmR
### address: 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
###

# Get balance of funding wallet for ETH
GET http://localhost:5040/funding-balance/0x0000000000000000000000000000000000000000

###

# Get balance of funding wallet for test tokens
GET http://localhost:5040/funding-balance/0x4E72770760c011647D4873f60A3CF6cDeA896CD8

###

# Fund 0.01 ETH to client at index 0 (requires funding wallet to have funds)
POST http://localhost:5040/fund
Content-Type: application/json

{
  "amount": "10000000000000000",
  "assetId": "0x0000000000000000000000000000000000000000",
  "publicIdentifier": "indra53QJ6exujj3pQQ8BPuTDfQqBXvpyzkz8uS4fwbNMtMZKQZWuUS"
}

###

# Fund 10 test tokens to client at index 0 (requires funding wallet to have funds)
POST http://localhost:5040/fund
Content-Type: application/json

{
  "amount": "10000000000000000000",
  "assetId": "0x4E72770760c011647D4873f60A3CF6cDeA896CD8",
  "publicIdentifier": "indra53QJ6exujj3pQQ8BPuTDfQqBXvpyzkz8uS4fwbNMtMZKQZWuUS"
}

###