# Transfer 10 test tokens directly from client at index 0 to client at index 1 (automatically resolved)
POST http://localhost:5040/linked-transfer
Content-Type: application/json

{
  "amount": "10000000000000000",
  "assetId": "0x4E72770760c011647D4873f60A3CF6cDeA896CD8",
  "recipient": "indra6FHtEpVbRgT221fN95REhxXHqeZrV4fJiv9TbG5FuwjrhUfcZ9",
  "publicIdentifier": "indra53QJ6exujj3pQQ8BPuTDfQqBXvpyzkz8uS4fwbNMtMZKQZWuUS"
}

###
