export const CONNEXT_MNEMONIC_STORE_KEY = "CONNEXT_MNEMONIC";
export const CONNEXT_INIT_OPTIONS_STORE_KEY = "CONNEXT_INIT_OPTIONS";
export const CONNEXT_SUBSCRIPTIONS_STORE_KEY = "CONNEXT_SUBSCRIPTIONS";
