export const CONNEXT_MNEMONIC_KEY = "mnemonic";
export const CONNEXT_INIT_OPTIONS_KEY = "initOptions";
export const CONNEXT_SUBSCRIPTIONS_KEY = "subscriptions";

export const CONNEXT_MNEMONIC_FILE_NAME = "CONNEXT_MNEMONIC.json";
export const CONNEXT_INIT_OPTIONS_FILE_NAME = "CONNEXT_INIT_OPTIONS.json";
export const CONNEXT_SUBSCRIPTIONS_FILE_NAME = "CONNEXT_SUBSCRIPTIONS.json";
